name: 'Deploy Infrastructure'

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TF_ACTION_WORKING_DIR: 'terraform'
      AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        working-directory: terraform
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    # Downloads a specific version of Terraform CLI and adds it to PATH
    - name: "Setup - Terraform CLI"
      uses: hashicorp/setup-terraform@v1

    # Init pulls credentials from the .aws/credentials file by default
    - name: "Run - Terraform Init"
      run: terraform init -input=false

    - name: "Run - Terraform Plan"
      id: plan
      run: terraform plan -input=false -no-color
      
    - name: "Run - Terraform Apply"
      run: terraform apply -input=false
